#!/bin/bash

#mission='inspection'
mission='robotics'

# Define the directories to work in
current_dir=`pwd`
base_dir="${HOME}/SimscapeSatelliteInspection"
util_dir="${base_dir}/SimscapeSatelliteInspection/slprj/ert/_sharedutils"
src_dir="${base_dir}/SimscapeSatelliteInspection/SatelliteServicing_Mission_ert_rtw"
build_dir="${base_dir}/SimscapeSatelliteInspection"

echo $util_dir
SatelliteServicing_Mission_robotics.mkecho $src_dir
echo $build_dir
# Copy required template files
rtwfile='rtwshared.mk'
mkfile='SatelliteServicing_Mission_'$mission'.mk'
cppfile='ert_main_'$mission'.cpp'

cp template_files/$rtwfile $util_dir
cp template_files/$cppfile $src_dir/ert_main.cpp
cp template_files/$mkfile $build_dir/SatelliteServicing_Mission.mk

# Make the utilities
cd $util_dir
make -f rtwshared.mk
cd $current_dir

# Make the shared object
cd $build_dir
make -f SatelliteServicing_Mission.mk
cd $current_dir
